apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "static-site.fullname" . }}
spec:
  secretName: {{ include "static-site.fullname" . }}-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - {{ .Values.app.domain }}
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ include "static-site.host" . }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer