{{- $fullName := include "static-site.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  namespace: default
spec:
  secretName: {{ $fullName }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - {{ .Values.certificateOrg }}
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ .Values.hostName }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer