apiVersion: v1
kind: Secret
metadata:
  name: {{ include "static-site.fullname" . }}-ecr
  annotations:
    replicator.v1.mittwald.de/replicate-from: ecr-login/ecr-login-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K