apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "static-site.fullname" . }}
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ include "static-site.host" . }}
      secretName: {{ include "static-site.fullname" . }}-tls
  rules:
    - host: {{ include "static-site.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "static-site.fullname" . }}
                port:
                  name: http