apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "static-site.fullname" . }}
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
imagePullSecrets:
  - name: {{ include "static-site.fullname" . }}-ecr