replicaCount: 2

# NOTE: always update this since this is meant to be a generic chart
app:
  name: ""
  version: ""
  domain: ""

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
